name: "Deploy GitHub Pages"
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v16.x
        uses: actions/setup-node@v1
        with:
          node_version: '16'
      - run: yarn install 
      - run: yarn build
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npx gh-pages@^3 -u "github-actions-bot <support+actions@github.com>" -d build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        